source 'https://rubygems.org'

gem 'middleman', '~> 4', '>= 4.1.11'
gem 'middleman-livereload', '~> 3', '>= 3.4.6'
gem 'middleman-syntax', '~> 3', '>= 3.2.0'
gem 'middleman-blog', '~> 4', '>= 4.0.0'

# Middleman has an undeclared dependency on `tzinfo-data` for
# generating timestamps.
#
# TODO(bbannier): Remove this explicit dependency when middleman
# correctly declares its requirements.
gem 'tzinfo-data'

gem 'rdiscount', '2.2.0.1'

gem 'htmlentities'

gem 'therubyracer'

gem 'rake'
